services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "${ENTRYPORT}:443"
    networks:
      - docker-network
    env_file:
      - .env
  mariadb:
    container_name: mariadb 
    build: requirements/mariadb
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
  wordpress:
    container_name: wordpress
      #build: requirements/wordpress
    build: 
      context: requirements/wordpress
      args:
        PHP_VER: ${PHP_VER}
        WP_VER: ${WP_VER}
    networks:
      - docker-network
          #volumes:
          #  - i dont know
    env_file:
      - .env

networks:
  docker-network:
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_MARIADB}
      o: bind
