services:

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    ports:
      - "${ENTRYPORT}:443"
    networks:
      - docker-network
    volumes:
      - wp:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb 
    build: requirements/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=${DB_USER}", "--password=${DB_PASS}"]
      interval: 3s
      timeout: 1s
      retries: 10
      start_period: 3s
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: 
      context: requirements/wordpress
      args:
        PHP_VER: ${PHP_VER}
        WP_VER: ${WP_VER}
    networks:
      - docker-network
    volumes:
      - wp:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  docker-network:
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DB}
      o: bind
  wp:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_WP}
      o: bind
