services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "${ENTRYPORT}:443"
    networks:
      - docker-network
    env_file:
      - .env
  mariadb:
    container_name: mariadb 
    build: requirements/mariadb
    networks:
      - docker-network
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env

networks:
  docker-network:
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_MARIADB}
      o: bind
